baseURL = "https://cronokirby.com/"
languageCode = "en-us"
title = "Cronokirby's Blog"
relativeURLs = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "xcode"
    tabWidth = 4

[taxonomies]
  tag = "tags"
  "note-tag" = "note-tags"
