baseURL = "https://cronokirby.com/"
languageCode = "en-us"
title = "Cronokirby's Blog"
relativeURLs = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
